enum ErrorMessage {
    NotFound = "Whoops. That page doesn't exist.",
    EmptyResponse = "Response is empty, this usually means that the page's DOM structure has changed.",
    InvalidRegion = "Invalid region.",
    InvalidSummonerName = "Invalid summoner name.",
    InvalidGameId = "Invalid game ID.",
    InvalidSummonerId = "Invalid summoner ID.",
    InvalidSeason = "Invalid season.",
    InvalidTimestamp = "Invalid timestamp.",
    InvalidGraphType = "Invalid graph type.",
    InvalidLeague = "Invalid league.",
    InvalidPeriod = "Invalid period.",
    InvalidMap = "Invalid map ID.",
    InvalidQueue = "Invalid queue.",
    InvalidChampionId = "Invalid champion ID.",
    InvalidChampionName = "Invalid champion name.",
    InvalidRole = "Invalid role.",
    InvalidApiKey = "Riot API key is invalid.",
    ParseFailed = "Failed to parse HTML.",
    InvalidResponse = "Invalid response received.",
    RateLimited = "Your request was rate limited by the client. Try again later.",
    Generic = "An undiagnosed error has occurred. Create an issue request with the steps to reproduce.",
    RiotApi = "Riot API returned an error, this usually means that your API key is incorrect.",
    NoResult = "The request was made, but returned no results.",
    ServiceUnavailable = "The requested service is unavailable. It is either down or slow to respond.",
}

enum HttpCode {
    Ok = 200,
    Forbidden = 403,
    BadRequest = 400,
    NotFound = 404,
    TimedOut = 408,
    Error = 500,
    TooManyRequests = 429,
    NoResults = 601,
    ServiceUnavailable = 503,
}

enum Region {
    NorthAmerica = "na",
    Korea = "kr",
    Japan = "jp",
    EuropeWest = "euw",
    EuropeNorth = "eune",
    Oceania = "oce",
    Brazil = "br",
    Las = "las",
    Lan = "lan",
    Russia = "ru",
    Turkey = "tr",
    Singapore = "sp",
    Indonesia = "id",
    Phillippines = "ph",
    Taiwan = "tw",
    Vietnam = "vn",
    Thailand = "th",
}

export { ErrorMessage, HttpCode, Region };
